# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(7, 7)
rand_tensor

tensor([[0.7923, 0.2308, 0.6315, 0.5650, 0.1167, 0.5010, 0.1640],
        [0.4463, 0.3683, 0.7601, 0.1112, 0.4652, 0.3822, 0.5048],
        [0.8841, 0.9385, 0.3727, 0.4542, 0.3703, 0.8806, 0.9825],
        [0.0823, 0.7088, 0.4215, 0.4189, 0.2860, 0.2356, 0.7076],
        [0.8604, 0.6991, 0.9575, 0.5488, 0.0286, 0.5904, 0.3510],
        [0.5818, 0.0239, 0.9560, 0.1589, 0.4068, 0.8135, 0.6313],
        [0.7469, 0.0752, 0.9733, 0.3961, 0.3784, 0.8708, 0.9864]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
another_tensor = torch.rand(1, 7)
# Perform matrix multiplication 
tensor_mm = torch.matmul(rand_tensor, another_tensor.T)
tensor_mm

tensor([[1.5557],
        [1.3254],
        [2.2472],
        [0.9364],
        [1.8907],
        [1.7343],
        [2.0650]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_a = torch.rand(7, 7)
rand_b = torch.rand(1, 7)

# Matrix multiply tensors
tensor_mm = torch.matmul(rand_a, rand_b.T)
tensor_mm


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(f"Is GPU available? {torch.cuda.is_available()}")
# Create two random tensors on GPU
tensor_a = torch.rand(2, 3).to("cuda")
tensor_b = torch.rand(2, 3).to("cuda")
tensor_a, tensor_b


Is GPU available? True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_a, tensor_b.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(f"Max: {result.max()}")
# Find min
print(f"Min: {result.min()}")

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(f"Arg max: {result.argmax()}")

# Find arg min
print(f"Arg min: {result.argmin()}")


Arg max: 3
Arg min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()


# Print out tensors and their shapes
print(tensor), print(tensor.shape)
print(tensor_squeezed), print(tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])


(None, None)